apiVersion: v1
kind: Namespace
metadata:
  name: cowboy
  labels:
    name: cowboy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowboy-django
  namespace: cowboy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowboy-django
  template:
    metadata:
      labels:
        app: cowboy-django
    spec:
      initContainers:
      - name: migrate
        image: dkdndes/cowboy-django:latest
        imagePullPolicy: Never
        command: ["uv", "run", "python", "manage.py", "migrate"]
      containers:
      - name: web
        image: dkdndes/cowboy-django:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cowboy-django
  namespace: cowboy
spec:
  selector:
    app: cowboy-django
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
  namespace: cowboy
  labels:
    app: nginx-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  namespace: cowboy
spec:
  selector:
    app: nginx-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
